name: Testing

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]
  workflow_dispatch:

permissions:
  contents: read

env:
  MAVEN_OPTS: -Xmx2g

jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./demo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run tests + JaCoCo check (threshold 60%)
        run: mvn -B -Dcoverage.threshold=0.60 clean verify

      - name: Upload JaCoCo HTML report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-testing
          path: '**/target/site/jacoco'

      - name: Validate Render secrets (safe checks)
        if: always()
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID_TESTING }}
        run: |
          if [ -z "$SERVICE_ID" ]; then
            echo "ERROR: SERVICE_ID está vacío. Revisa el secret RENDER_SERVICE_ID_TESTING" >&2
            exit 1
          fi
          prefix="${SERVICE_ID:0:4}"
          echo "SERVICE_ID prefix: $prefix"
          if [ "$prefix" != "srv-" ]; then
            echo "ERROR: SERVICE_ID no parece un service id válido (debe empezar por 'srv-')." >&2
            echo "Revisa que hayas guardado el Service ID (srv-...) y no el nombre del servicio." >&2
            exit 1
          fi

          if [ -z "$RENDER_API_KEY" ]; then
            echo "ERROR: RENDER_API_KEY vacío. Revisa el secret RENDER_API_KEY" >&2
            exit 1
          fi
          # detectar newline/carriage return
          if printf '%s' "$RENDER_API_KEY" | grep -q $'\n'; then
            echo "ERROR: RENDER_API_KEY contiene saltos de línea. Re-crear el secret sin newlines." >&2
            exit 1
          fi

          echo "Checks OK (no se ha impreso ningún secreto)."
            echo "Failed to trigger deploy. Response body:" >&2
            echo "$body_resp" >&2
            exit 1
          fi
