name: Testing

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]
  workflow_dispatch:

permissions:
  contents: read

env:
  MAVEN_OPTS: -Xmx2g

jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./demo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run tests + JaCoCo check (threshold 60%)
        run: mvn -B -Dcoverage.threshold=0.60 clean verify

      - name: Upload JaCoCo HTML report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-testing
          path: '**/target/site/jacoco'

      - name: Trigger Render deploy via hook
        if: success()
        env:
          DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_TESTING }}
        run: |
          curl -s -X POST "${DEPLOY_HOOK_URL}"


